### ISSUE TITLE
OP is an actual moron

### ISSUE THREAD

**Issue by hazycora** [normanlol/darker-discord#1]
Guys, I think OP is an actual moron. I mean like, ancient textbook definition moron. 
Now, I'm not trying to be rude or anything, but I have reason to believe that OP actually has an IQ under 70.

**Comment by normanlol** [comment]
this is me when im driving

**Comment by hazycora** [comment]
> this is me when im driving

Okay, now I think you're a bit confused. See, you're probably on a computer right now. You could also be on a mobile device, but what device you are on doesn't matter too much. What does matter though is that if you were driving right now you couldn't legally be using a phone at the same time.
Now, you could be saying this is how you _would_ act if you were driving. Now, if we assume this is the meaning of your comment, we would have to also assume that there is some meaning to justify typing it.
Some possible meanings include:
- you thought this would be funny
- you thought this would brighten my day
- you are a cruel human being
- you like to make people sad
- you gave up on things having meaning

Now, I should make this clear right from the start. None of these options make _any_ sense. In case you don't believe me, here's a run down.
## You thought this would be funny
If you thought this would be funny, this only proves your IQ level is under 70. Case closed!
## You thought this would brighten my day
You should know the world well enough to know that random absurdist statements such as these aren't what people want to see. IQ under 70, case closed.
## You are a cruel human being
You may have said this in order to make me feel bad.
Only villains would do such a thing. Only the worst of the worst. IQ under 70.
## You like to make people sad
See above point.
## You gave up on things having meaning
Well you are dumb for doing that, I think we can all agree.

Now, with all these points clearly spelled out and illustrated for you, what was your fucking reason for typing this shit

**Comment by normanlol** [comment]
this is me when im driving

**Comment by hazycora** [comment]
> this is me when im driving

You bitch. You slut. You whore.
You're everything I don't like about the internet. You're why parents tell their kids "don't trust the internet". Yes, you are the one and only reason.
Everyone knows what a troll is. Now, the meaning of the word does change over time, and the word isn't used too often anymore, but that doesn't make the term any less useful. We'll be using this term to dissect why you (or OP) are the way that you are.
To quote [Wikipedia](https://en.wikipedia.org/wiki/Internet_troll?wprov=sfla1), 
### In Internet slang, a troll is a person who starts flame wars or intentionally upsets people on the Internet by posting inflammatory and digressive, extraneous, or off-topic messages in an online community (such as a newsgroup, forum, chat room, or blog) with the intent of provoking readers into displaying emotional responses and normalizing tangential discussion, either for the troll's amusement, or to achieve a specific result such as disrupting a rival's online activities or manipulating a political process.
Now, this may be a long quote for some, perhaps those that are too lazy to read the full comment before sending a reply, but for any animal capable of being classified as _"human"_ this quote is not of particular length. Still, for those incapable of intelligent thought, here's a summary. 
### A troll is a person that sends frustrating messages (whether they are off-topic, purposely ignorant, or some other means of frustrating the reader) on an online community.
Judging from the length of my reply thus far, you may be able to guess I am frustrated. If you came to this conclusion, congratulations! You may be able to get a job at [Culver's](https://www.culvers.com/). For those who may have come to a different conclusion, _and for those who came to no conclusion at all_, you have proven to be of low intelligence. OP clearly is the cause of my frustrations, proving OP has one of the properties of an online troll.
Secondly, your message was certainly ignorant. Certainly off-topic. "this is me when I'm driving"? Nobody had said anything about driving, let alone how you are while you drive. This message proves to be ignorant of the topic at hand, and is therefore off-topic.

## Now, that should be enough to prove Norman is a textbook moron.
But unfortunately, I still have one more question to answer. 
_and this may be tricky..._
Wikipedia defines a troll to be someone who makes off-topic, hurtful, or ignorant messages on an online forum or community. For most readers, Github should count. For less thoughtful readers, it may not count. We'll have to define **Community**.
fuck it i was gonna quote wikipedia again and all this shit but im so fucking done i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit

**Comment by normanlol** [comment]
> 
> 
> > this is me when im driving
> 
> You bitch. You slut. You whore.
> You're everything I don't like about the internet. You're why parents tell their kids "don't trust the internet". Yes, you are the one and only reason.
> Everyone knows what a troll is. Now, the meaning of the word does change over time, and the word isn't used too often anymore, but that doesn't make the term any less useful. We'll be using this term to dissect why you (or OP) are the way that you are.
> To quote [Wikipedia](https://en.wikipedia.org/wiki/Internet_troll?wprov=sfla1),
> ### In Internet slang, a troll is a person who starts flame wars or intentionally upsets people on the Internet by posting inflammatory and digressive, extraneous, or off-topic messages in an online community (such as a newsgroup, forum, chat room, or blog) with the intent of provoking readers into displaying emotional responses and normalizing tangential discussion, either for the troll's amusement, or to achieve a specific result such as disrupting a rival's online activities or manipulating a political process.
> 
> Now, this may be a long quote for some, perhaps those that are too lazy to read the full comment before sending a reply, but for any animal capable of being classified as _"human"_ this quote is not of particular length. Still, for those incapable of intelligent thought, here's a summary.
> ### A troll is a person that sends frustrating messages (whether they are off-topic, purposely ignorant, or some other means of frustrating the reader) on an online community.
> 
> Judging from the length of my reply thus far, you may be able to guess I am frustrated. If you came to this conclusion, congratulations! You may be able to get a job at [Culver's](https://www.culvers.com/). For those who may have come to a different conclusion, _and for those who came to no conclusion at all_, you have proven to be of low intelligence. OP clearly is the cause of my frustrations, proving OP has one of the properties of an online troll.
> Secondly, your message was certainly ignorant. Certainly off-topic. "this is me when I'm driving"? Nobody had said anything about driving, let alone how you are while you drive. This message proves to be ignorant of the topic at hand, and is therefore off-topic.
> ## Now, that should be enough to prove Norman is a textbook moron.
> 
> But unfortunately, I still have one more question to answer.
> _and this may be tricky..._
> Wikipedia defines a troll to be someone who makes off-topic, hurtful, or ignorant messages on an online forum or community. For most readers, Github should count. For less thoughtful readers, it may not count. We'll have to define **Community**.
> fuck it i was gonna quote wikipedia again and all this shit but im so fucking done i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit

this is me when im driving

**Comment by hazycora** [comment]
> > 
> > 
> > > this is me when im driving
> > 
> > You bitch. You slut. You whore.
> > You're everything I don't like about the internet. You're why parents tell their kids "don't trust the internet". Yes, you are the one and only reason.
> > Everyone knows what a troll is. Now, the meaning of the word does change over time, and the word isn't used too often anymore, but that doesn't make the term any less useful. We'll be using this term to dissect why you (or OP) are the way that you are.
> > To quote [Wikipedia](https://en.wikipedia.org/wiki/Internet_troll?wprov=sfla1),
> > ### In Internet slang, a troll is a person who starts flame wars or intentionally upsets people on the Internet by posting inflammatory and digressive, extraneous, or off-topic messages in an online community (such as a newsgroup, forum, chat room, or blog) with the intent of provoking readers into displaying emotional responses and normalizing tangential discussion, either for the troll's amusement, or to achieve a specific result such as disrupting a rival's online activities or manipulating a political process.
> > 
> > Now, this may be a long quote for some, perhaps those that are too lazy to read the full comment before sending a reply, but for any animal capable of being classified as _"human"_ this quote is not of particular length. Still, for those incapable of intelligent thought, here's a summary.
> > ### A troll is a person that sends frustrating messages (whether they are off-topic, purposely ignorant, or some other means of frustrating the reader) on an online community.
> > 
> > Judging from the length of my reply thus far, you may be able to guess I am frustrated. If you came to this conclusion, congratulations! You may be able to get a job at [Culver's](https://www.culvers.com/). For those who may have come to a different conclusion, _and for those who came to no conclusion at all_, you have proven to be of low intelligence. OP clearly is the cause of my frustrations, proving OP has one of the properties of an online troll.
> > Secondly, your message was certainly ignorant. Certainly off-topic. "this is me when I'm driving"? Nobody had said anything about driving, let alone how you are while you drive. This message proves to be ignorant of the topic at hand, and is therefore off-topic.
> > ## Now, that should be enough to prove Norman is a textbook moron.
> > 
> > But unfortunately, I still have one more question to answer.
> > _and this may be tricky..._
> > Wikipedia defines a troll to be someone who makes off-topic, hurtful, or ignorant messages on an online forum or community. For most readers, Github should count. For less thoughtful readers, it may not count. We'll have to define **Community**.
> > fuck it i was gonna quote wikipedia again and all this shit but im so fucking done i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit
> 
> this is me when im driving

i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit i hate this shit
